[package]
name = "yaml-hash"
version = "0.4.4"
edition = "2021"
description = "Improved YAML Hash"
repository = "https://github.com/qtfkwk/yaml-hash"
license = "MIT"

[dependencies]
anyhow = "1.0.96"
yaml-rust2 = "0.10.0"
